import test from 'node:test';
import assert from 'node:assert/strict';
import { influenceFields, parseInfluenceFields, modifierFields, parseInfluenceOperation, editInfluenceRows, renderInfluenceFields, renderTerritoryInfluence } from '../../src/ui/domain-patterns/diplomacy/territory-influence-form.js';
import { changeTerritoryState, emptyTerritoryState, projectTerritoryState, resolveTerritoryInfluence } from '../../src/territory/territory-state.js';
import { DiplomacyApplicationController, DiplomacyApplication } from '../../src/ui/domain-patterns/diplomacy/diplomacy-app.js';
import { territoryLinkIntentVisible } from '../../src/diplomacy/territory-link-visibility.js';
const unwrap = (r:any):any => { assert.equal(r.ok,true,JSON.stringify(r)); return r.value; };
const source = { type:'manual',id:'ui' };
const fields = (patch = {}) => ({ ...influenceFields(), influencePartyRef:'JournalEntry.party', reason:'Influência', influenceRevision:'0', ...patch });
const parse = (patch = {}) => parseInfluenceFields(fields(patch),10,'inf',source);
const influence = () => unwrap(parse()).value;
const state = () => ({ ...emptyTerritoryState({ schemaVersion:1,uuid:'JournalEntry.region',revision:0,label:'Region',kind:'domain-manager:region',scale:'region',visibility:'public',createdAt:0,updatedAt:0,locatedInUuid:null,administrativeParentUuid:null,geography:{},hierarchyHistory:[] }), influence:[influence()] });
const ctx = (s:any) => ({ expectedRevision:s.territory.revision,eventId:crypto.randomUUID(),at:s.territory.updatedAt+1,worldTick:10,reason:'change',sourceRefs:[source] });
const change = (s:any,a:any) => unwrap(changeTerritoryState(s,ctx(s),a));
const mod = (patch={}) => ({ ...modifierFields(),kind:'add-influence-modifier',influenceId:'inf',modifier_axis:'domain-manager:political',modifier_delta:'5', ...patch });
function controller(isGm=true) {
 const calls:any[]=[]; const api:any={territory:{ modify:async(p:any)=>{ calls.push(p); return {ok:true,value:{}}; } },proposals:{submit:async(p:any)=>{calls.push(p);return {ok:true,value:{}};} } };
 const c=new DiplomacyApplicationController(api); c.selectTab('territory'); c.select('JournalEntry.region'); c.detail={id:'JournalEntry.region',revision:0,worldTick:10,influence:[influence()]}; c.list={isGm}; return {c,calls};
}
test('influence UI: defaults roundtrip complete source with zero base and explicit tick',()=>{ const i=influence();assert.equal(i.axes[0].base,0);assert.equal(i.startsAtWorldTick,10);assert.deepEqual(unwrap(parseInfluenceFields(influenceFields(i),99,i.id,i.sourceRef)).value,i); });
test('influence UI: invalid party, visibility, duplicate axes and unsafe bounds reject',()=>{ for(const p of [{influencePartyRef:''},{influencePartyType:'bad'},{influenceVisibility:'bad'},{axis_0_base:'1.5'},{axis_0_minimum:'1'},{axis_0_maximum:'-1'},{axis_0_base:String(Number.MAX_SAFE_INTEGER+1)},{axis_0_id:'bad'}])assert.equal(parse(p).ok,false);const f=unwrap(editInfluenceRows(fields(),'axis','add'));f.axis_1_id=f.axis_0_id;assert.equal(parseInfluenceFields(f,10,'inf',source).ok,false); });
test('influence UI: axes remain independent and row edits preserve existing fields',()=>{let f=unwrap(editInfluenceRows(fields({reason:'keep'}),'axis','add'));f.axis_1_id='domain-manager:trade';assert.equal(unwrap(parseInfluenceFields(f,10,'inf',source)).value.axes.length,2); f=unwrap(editInfluenceRows(f,'axis','remove',0));assert.equal(f.axis_0_id,'domain-manager:trade');assert.equal(f.reason,'keep');assert.equal(editInfluenceRows(f,'axis','remove',0).ok,false);});
test('influence UI: decadence validates period baseline and explicit origin',()=>{const p={axis_0_decay:'on',axis_0_amount:'2',axis_0_period:'3',axis_0_baseline:'0',axis_0_base:'20'};assert.equal(unwrap(parse(p)).value.axes[0].decay.fromWorldTick,10);for(const q of [{axis_0_period:'0'},{axis_0_amount:'-1'},{axis_0_baseline:'101'},{axis_0_from:'1.5'}])assert.equal(parse({...p,...q}).ok,false);});
test('influence UI: temporal window excludes invalid and accepts zero',()=>{assert.equal(unwrap(parse({influenceStarts:'0',influenceExpires:'1'})).value.startsAtWorldTick,0);for(const p of [{influenceExpires:'10'},{influenceStarts:'-1'},{influenceExpires:'1.5'}])assert.equal(parse(p).ok,false);});
test('influence UI: dangling axis modifier is explicit error and no silently deleted row',()=>{let f=unwrap(editInfluenceRows(fields(),'modifier','add'));f.modifier_0_axis='domain-manager:missing';f.modifier_0_delta='1';assert.equal(parseInfluenceFields(f,10,'inf',source).ok,false);f.modifier_0_axis='domain-manager:political';assert.equal(unwrap(parseInfluenceFields(f,10,'inf',source)).value.modifiers.length,1);});
test('influence operations: add and end preserve base and append history, repeat end is no-op',()=>{let s:any=state();const a=unwrap(parseInfluenceOperation(mod(),s.influence,10,'mod',source));s=change(s,a);assert.equal(s.influence[0].axes[0].base,0);assert.equal(resolveTerritoryInfluence(s,10,()=>true)[0].value,5);s=change(s,{kind:'end-influence-modifier',id:'inf',modifierId:'mod'});assert.equal(resolveTerritoryInfluence(s,10,()=>true)[0].value,0);assert.equal(change(s,{kind:'end-influence-modifier',id:'inf',modifierId:'mod'}).events.length,s.events.length);assert.equal(JSON.parse(JSON.stringify(s)).events.length,2);});
test('influence operations: duplicate, malformed, missing axis and inactive target reject',()=>{let s:any=state();const a=unwrap(parseInfluenceOperation(mod(),s.influence,10,'mod',source));s=change(s,a);assert.equal(changeTerritoryState(s,ctx(s),a).ok,false);assert.equal(changeTerritoryState(s,ctx(s),{...a,value:{...a.value,axisId:'domain-manager:missing'}}).ok,false);s=change(s,{kind:'end-influence',id:'inf'});assert.equal(changeTerritoryState(s,ctx(s),{...a,value:{...a.value,id:'new'}}).ok,false);assert.equal(resolveTerritoryInfluence(s,10,()=>true).length,0);});
test('influence UI: escaped rendering and inactive checkbox preserved',()=>{const html=renderInfluenceFields(fields({reason:'<script>',influencePartyRef:'<script>',influenceActive:''}));assert.equal(html.includes('<script>'),false);assert.equal(html.includes('name="influenceActive" checked'),false);assert.ok(renderTerritoryInfluence({...state(),revision:0},10,false,{}, {},{}).includes('Enviar proposta ao GM'));});
test('influence UI controller: GM direct, player proposal, reason/revision validation',async()=>{for(const gm of [true,false]){const {c,calls}=controller(gm);assert.equal((await c.submitInfluence(fields(),'influence')).ok,true);const intent=gm?calls[0]:calls[0].intent;assert.equal(intent.action.kind,'influence');assert.equal(intent.expectedRevision,0);}const {c,calls}=controller();assert.equal((await c.submitInfluence(fields({influenceRevision:'1'}),'influence')).ok,false);assert.equal((await c.submitInfluence(fields({reason:' '}),'influence')).ok,false);assert.equal(calls.length,0);assert.equal(c.influenceDrafts.influence.reason,' ');});
test('influence UI controller: same failed draft retains ID and context change clears it',async()=>{const {c,calls}=controller();(c.api as any).territory.modify=async(p:any)=>{calls.push(p);return {ok:false,error:{code:'FAIL',message:'fail'}};};await c.submitInfluence(fields(),'influence');await c.submitInfluence(fields(),'influence');assert.equal(calls[0].action.value.id,calls[1].action.value.id);c.select('JournalEntry.other');assert.deepEqual(c.influenceDrafts,{});});
test('influence privacy: projected modifiers and secret source never reach resolver',()=>{let s:any=state();const a=unwrap(parseInfluenceOperation(mod({modifier_visibility:'secret'}),s.influence,10,'private',source));s=change(s,a);const projected=projectTerritoryState(s,v=>v==='public')!;assert.equal(projected.influence[0].modifiers.length,0);assert.equal(resolveTerritoryInfluence(projected,10,v=>v==='public')[0].value,0);});
test('influence admission: secret and missing targets share rejection',async()=>{const s:any=state();s.influence[0].visibility='secret';const context:any={senderUserId:'player'};const options:any={domains:{read:async()=>({ok:false})},controllers:{}};for(const id of ['inf','missing'])assert.equal(await territoryLinkIntentVisible({mode:'modify',action:{kind:'end-influence',id}} as any,s,context,options),false);});

test('influence bindings: form routes, unchecked active persists, rows and end-mode switching keep current draft', async()=>{
 const {c}=controller(),app=new DiplomacyApplication({api:c.api}),listeners:Record<string,Function>={},saved=globalThis.FormData;
 app.controller.selectTab('territory');app.controller.select(c.detail.id);app.controller.detail=c.detail;app.controller.list=c.list;
 (app as any).element={addEventListener:(e:string,fn:Function)=>listeners[e]=fn};(app as any).render=async()=>{};
 (globalThis as any).FormData=class {constructor(readonly form:any){}forEach(fn:Function){Object.entries(this.form.values).forEach(([k,v])=>fn(v,k));}};
 const form=(name:string,values:any)=>({dataset:{dmForm:name},values,querySelectorAll:()=>[{name:'influenceActive',checked:false}]});
 try{(app as any)._onRender();const f=form('territory-influence',fields());listeners.input({target:{closest:()=>f}});assert.equal(app.controller.influenceDrafts.influence.influenceActive,'');
 await listeners.click({target:{closest:()=>({dataset:{dmInfluenceRows:'axis',dmInfluenceOperation:'add'},closest:()=>f})}});assert.equal(app.controller.influenceDrafts.influence.influenceAxisCount,'2');
 for(const endKind of ['end-influence','end-influence-modifier']){const f=form('territory-influence-end',{influenceId:'inf',endKind});await listeners.change({target:{dataset:{dmInfluenceTarget:'true'},closest:()=>f}});assert.equal(app.controller.influenceDrafts['end-influence'].endKind,endKind);}
 await listeners.submit({target:form('territory-influence',fields()),preventDefault(){}});await listeners.click({target:{closest:()=>({dataset:{dmInfluenceReset:'true'}})}});assert.deepEqual(app.controller.influenceDrafts,{});
 }finally{(globalThis as any).FormData=saved;}
});
